name: "heart_rate_monitor"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    depends_on:
      - postgres
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

  postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heart_rate_monitor_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
